### ISSUE TITLE
Provide more information in the tokenizer (added to the Token)

### ISSUE THREAD

**Issue by Specy** [umut-sahin/dotlr#13]
Most parsers have information on a token that tell you at what position the token is in. for example in this tokenized string (tokens separated by a |):
```
foo|(|bar|+|baz|)
```
`foo`: offset 0, len 3 (optional, can be derived from the slice itself
`(`: offset 3, len 1
`bar`: offset: 4, len 3

etc...
Other useful proprieties are `start line, end line, start column, end column`

Also, does the parser ignore whitespace? `foo(bar+baz)` and `foo(bar + baz)` tokenize the same.
The offset information is useful to create things like this: 
![image](https://github.com/user-attachments/assets/21c9b0a3-248e-4a7f-bde7-5a7befe28883)
I was calculating the offset myself but since whitespace seems to be ignored, the tokens positions are wrong, this would be solved with the offsets.

This should also help with #1

**Comment by umut-sahin** [comment]
Yeap, this should be done, for sure. I'll try to take a look this weekend.
