### ISSUE TITLE
Wasm support

### ISSUE THREAD

**Issue by Specy** [umut-sahin/dotlr#8]
I wanted to use the library on the web to create a website, that needs the library to be compiled as a wasm module, I'm not sure if this is better implemented directly in the library or if it's better to make another one wrapping this one, what do you think? I can help with the wasm implementation

**Comment by Specy** [comment]
I'm trying to work on the wasm compilation here https://github.com/Specy/dotlr, currently the main issue is that there are some features that only work natively, i've narrowed it down to the crates: `"clap", "dirs", "rustyline", "colored"`, i've removed them in the `wasm` feature, but the `colored` lib was not a optional lib and it is being used in a few places that would require either a lot of code duplication with cfg flags, or maybe abstracted away to be optional. An example of this is the usage of `.green()` and `.cyan()`  in the Errors file

**Comment by umut-sahin** [comment]
> I wanted to use the library on the web to create a website, that needs the library to be compiled as a wasm module

That's super cool, yeah let's do it!

> I'm not sure if this is better implemented directly in the library or if it's better to make another one wrapping this one, what do you think?

I think it's better to implement it here, it will probably need some changes an external library can't make on it's own. 

> I can help with the wasm implementation

Amazing, I saw your PR and I'll review it soon!

**Comment by umut-sahin** [comment]
> For now i fixed this issue by converting (...).green() into str_green(...) and using cfg flags to do a noop when using wasm https://github.com/Specy/dotlr/blob/main/src/utils.rs, not the best solution but...

I think you should be able to simulate it with a little trick:

```rust
#[cfg(target_family = "wasm")]
pub trait MockColored {
    fn green(&self) -> String;
    /// ... and others
}

#[cfg(target_family = "wasm")]
impl<T: AsRef<str>> MockColored for T {
    fn green(&self) -> String {
        self.as_ref().to_owned()
    }
    // ... and others
}
```

Then in wasm, colored would be disabled. You can do this with:
```
[target.'cfg(not(target_family = "wasm"))'.dependencies]
colored = { version = "2.1" }
```
and remove it from regular dependencies.

Let me know how it goes, and I'm sure we can find a workaround.

**Comment by Specy** [comment]
I managed to solve that issue of mocking and i've replaced it in the library. 

I also started working on the website, currently it's not much been implemented, only the handling of the project plus an editor for the input and the grammar, and a very easy visualization.
[you can try it here!](https://tokeko.specy.app/projects/share?project=N4IgbgpgTgzglgewHYgFwEYA0I4BM0gwAWAhlBCNkiQLYWogAqUcJANgAQAOUCAVhADGAF0ohcEGIJZdhiFAzHSIJYRFwBBURgDsAJgBsAZgAM+gCw7zerCACuXXKvVa06fcbOHT5k9kHIakjaIABmCAgAFABGZBwA1ByxAF4AlGIA5lC0NGQEAAocALQAfBwAogA6UJVI1bXlxWWNAOTxLRyM9UiNpZ3d3YxNHACkeBwtkR2tqS2Dw2O4AzVIi8MA9ADaGkUAWiRFyQC623sHySZFAJxH8esgAL5AA)

I plan on adding FIRST/FOLLOW/etc... visualization, and a tree view of the parse tree

**Comment by Specy** [comment]
Ok so the website is fully complete, there are a few more things i wish to implement but those need to be worked on the dotlr library itself (epsilon transitions, LR0 parser, more token info), after the wasm PR is finished i'll continue with the rest

**Comment by umut-sahin** [comment]
Done in #10
